name: CI/CD for statis WebSite # title a pipeline

on: # Here we specify when to launch a workflow
  push:
    branches: [ main ]

jobs: # tasks to complete section
  hello-world: # title a task
    runs-on: ubuntu-latest

    # steps to follow
    steps:
     - name: Checkout code # what is a string?
       uses: actions/checkout@v3 # cloning my repository into a virtual machine

     - name: Deploy to Github Pages
       uses: peaceiris/actions-gh-pages@v3
       with:
         github_token: ${{ secrets.GITHUB_TOKEN }}
         publish_di: ./

     - name: Show date
       run: date